import * as THREE from 'three';
const $=id=>document.getElementById(id);
const names={greninja:'Mega Greninja',fusion:'Lucario × Raichu',godzilla:'Godzilla',charizard:'Mega Charizard X',lucario:'Mega Lucario',raichu:'Raichu',venusaur:'Mega Venusaur',dragonfusion:'Charizard × Mega Lucario',eevee:'Ribbon Eevee',surfer:'Surfer Pikachu',rhyhorn:'Rhyhorn',thermal:'Thermal Godzilla',princess:'Princess Aurora'};
let state={hero:'greninja',enemy:'godzilla',hp:120,ehp:150,max:150,phase:'ready',age:0,turn:0,guard:false,paused:false};
const held=new Set(),touchHeld=new Map();
function clearControls(){held.clear();touchHeld.clear()}
function directionHeld(key){return held.has(key)||[...touchHeld.values()].includes(key)}
function movementKey(e){return /^Key[WASD]$/.test(e.code)?e.code.slice(3).toLowerCase():e.key.length===1?e.key.toLowerCase():e.key}
const obstacles=[{x:-1.1,z:1.7,r:.7},{x:1.1,z:-1.7,r:.7},{x:0,z:0,r:.48}];
let realtime=true,teamsEnabled=false,heroReserveChoice="eevee",enemyReserveChoice="venusaur";
let renderer=null,scene,camera,hero,enemy,fxGroup,orbit=0,clock=new THREE.Clock(),worldTime=0;
const canvas=$('battle'),colors={ink:0x172939,blue:0x176dc3,navy:0x182750,cyan:0x51e9fa,pink:0xf96fa7,yellow:0xffd33d,orange:0xffa23a};
const materials=new Map();function material(c){if(!materials.has(c))materials.set(c,new THREE.MeshToonMaterial({color:c}));return materials.get(c)}
const boxGeo=new THREE.BoxGeometry(1,1,1),ballGeo=new THREE.SphereGeometry(1,10,8),coneGeo=new THREE.ConeGeometry(1,1,4),cylGeo=new THREE.CylinderGeometry(1,1,1,12);
function shape(g,geo,c,p,s,outline=true){const m=new THREE.Mesh(geo,material(c));m.position.set(...p);m.scale.set(...s);g.add(m);if(outline){const o=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:colors.ink,side:THREE.BackSide}));o.scale.setScalar(1.06);m.add(o)}return m}
function block(g,c,p,s,stud=false){const m=shape(g,boxGeo,c,p,s);if(stud){for(const x of [-.27,.27])shape(g,cylGeo,c,[p[0]+x*s[0],p[1]+s[1]/2+.06,p[2]],[.12,.13,.12],false)}return m}
function ball(g,c,p,s){return shape(g,ballGeo,c,p,s)}
function triangle(g,c,p,s){return shape(g,coneGeo,c,p,s)}
function eyes(g,y,z,wide=.27){for(const side of [-1,1]){block(g,0xffffff,[side*wide,y,z],[.29,.22,.07]);block(g,0x122133,[side*wide,y-.015,z+.055],[.095,.15,.04])}}
function creature(kind){const root=new THREE.Group(),body=new THREE.Group();root.add(body);let head=new THREE.Group();body.add(head);head.position.y=1.45;const limbs=[];let emblem;
 if(kind==='venusaur'||kind==='rhyhorn'||kind==='eevee'){
  const c=kind==='venusaur'?0x58a988:kind==='rhyhorn'?0x9aabbc:0xb87645;block(body,c,[0,.75,0],[1.5,.9,1.4],true);head.position.set(0,.95,.65);block(head,c,[0,.05,.12],[1.2,.7,.85],true);eyes(head,.15,.59,.34);for(const x of[-.55,.55])for(const z of[-.48,.55])limbs.push(block(body,c,[x,.24,z],[.38,.48,.45]));
  if(kind==='venusaur'){block(body,0x885a3a,[0,1.65,-.25],[.35,1.3,.35]);for(let i=0;i<6;i++){const a=i*Math.PI/3,leaf=triangle(body,0x32815c,[Math.sin(a)*.6,1.35,-.25+Math.cos(a)*.6],[.7,1.35,.2]);leaf.rotation.set(Math.PI/2,a,0);const petal=block(body,0xfa7fa0,[Math.sin(a)*.52,2.25,-.25+Math.cos(a)*.52],[.65,.22,.85]);petal.rotation.y=a}ball(body,0xffd957,[0,2.4,-.25],[.42,.23,.42])}
  if(kind==='rhyhorn'){const horn=triangle(head,0xf0e5c9,[0,.3,.73],[.28,.8,.3]);horn.rotation.x=Math.PI/2;for(let i=0;i<3;i++)triangle(body,0xc6d3dd,[0,1.36,-.48+i*.4],[.36,.48,.35]);block(head,0x748494,[0,-.17,.52],[1.2,.18,.4])}
  if(kind==='eevee'){for(const side of[-1,1]){const ear=triangle(head,0x70442c,[side*.44,.78,-.1],[.32,1.15,.24]);ear.rotation.z=-side*.32}block(body,0xffe4b9,[0,1.02,.57],[1.6,.32,.4]);const hat=shape(head,cylGeo,0xffffff,[0,.6,0],[.87,.16,.72]);block(head,0xff96c6,[0,.87,0],[.9,.5,.65],true);for(const side of[-1,1]){const bow=triangle(head,0xff5d9b,[side*.23,.84,.42],[.35,.47,.14]);bow.rotation.z=side*Math.PI/2}ball(head,0xffffff,[0,.83,.49],[.13,.13,.1]);block(body,0xffe4b9,[0,1,-1],[.7,.6,.8])}
 }else if(kind==='surfer'||kind==='princess'){
  const princess=kind==='princess',c=princess?0xf095ca:0xffd84b;block(body,c,[0,.85,0],[.85,1.15,.65],true);head.position.y=1.65;block(head,princess?0xffd6b1:c,[0,.1,0],[.95,.65,.7],true);eyes(head,.16,.39,.28);for(const side of[-1,1]){limbs.push(block(body,c,[side*.32,.15,.1],[.28,.3,.5]));limbs.push(block(body,c,[side*.6,.95,0],[.23,.75,.25]))}if(princess){shape(body,coneGeo,0xc978db,[0,.55,0],[.78,1.1,.7]);block(head,0x764b38,[0,.23,-.25],[1.08,.95,.45]);block(head,0xffd84b,[0,.6,0],[1,.18,.7]);for(let i=-1;i<=1;i++)triangle(head,0xffd84b,[i*.3,.86,.13],[.22,.4,.18]);block(body,0xffeab5,[.8,1.05,.12],[.1,1.6,.1]);ball(body,0x78ecf3,[.8,1.92,.12],[.22,.22,.15])}else{for(const side of[-1,1]){const ear=triangle(head,0xffd84b,[side*.39,.8,0],[.23,1.1,.2]);ear.rotation.z=-side*.2;ball(head,0xf45a47,[side*.43,-.03,.38],[.15,.14,.05])}const board=block(body,0x51d9ef,[0,.04,0],[.9,.13,2.5]);board.rotation.y=.25;block(body,0xffdc35,[.64,1,-.5],[.55,.25,.14]).rotation.z=.7;block(body,0xffdc35,[.89,1.27,-.5],[.25,.6,.14])}
 }else if(kind==='greninja'){
  block(body,colors.navy,[0,.91,0],[.75,.91,.57],true);block(body,0xf5dd91,[0,.9,.32],[.42,.55,.08]);block(head,colors.blue,[0,.2,0],[1.06,.6,.67],true);eyes(head,.22,.37,.31);
  for(const side of [-1,1]){const horn=triangle(head,colors.blue,[side*.5,.66,-.12],[.27,.65,.24]);horn.rotation.z=-side*.55;const foot=block(body,colors.blue,[side*.47,.15,.12],[.65,.24,.77]);limbs.push(foot);const arm=block(body,colors.blue,[side*.64,.95,.08],[.22,.8,.23]);arm.rotation.z=side*.45;limbs.push(arm);ball(body,colors.cyan,[side*.83,.63,.13],[.18,.12,.2])}
  block(body,colors.pink,[0,1.37,0],[.98,.18,.75]);const scarf=block(body,colors.pink,[.85,1.25,-.32],[1.2,.2,.22]);scarf.rotation.z=-.16;
  emblem=new THREE.Group();body.add(emblem);emblem.position.set(0,1.1,-.65);for(let i=0;i<4;i++){const blade=triangle(emblem,colors.cyan,[Math.sin(i*Math.PI/2)*.6,Math.cos(i*Math.PI/2)*.6,0],[.38,.95,.12]);blade.rotation.z=-i*Math.PI/2}ball(emblem,0xdbffff,[0,0,0],[.23,.23,.12]);
 }else if(kind==='fusion'||kind==='lucario'||kind==='raichu'){
  const fusion=kind==='fusion'||kind==='raichu',c=fusion?colors.orange:0x49a4d9;block(body,c,[0,.98,0],[.72,1.03,.58],true);block(body,0xffe6a2,[0,1.02,.35],[.65,.55,.16]);head.position.y=1.66;block(head,c,[0,.13,0],[.9,.56,.66],true);block(head,colors.navy,[0,.1,.35],[1,.23,.1]);eyes(head,.14,.43,.28);
  for(const side of [-1,1]){const ear=triangle(head,fusion?colors.yellow:colors.navy,[side*.34,.73,-.06],[.27,1,.22]);ear.rotation.z=side*-.18;block(head,colors.ink,[side*.52,-.15,-.28],[.2,.5,.16]);limbs.push(block(body,colors.navy,[side*.35,.23,.05],[.32,.45,.58]));const arm=block(body,c,[side*.57,1,.1],[.25,.75,.29]);arm.rotation.z=side*.25;limbs.push(arm);triangle(body,0xffffff,[side*.64,.92,.32],[.17,.26,.17]);if(fusion)ball(head,colors.yellow,[side*.43,-.05,.37],[.16,.13,.07])}
  const spike=triangle(body,0xffffff,[0,1.03,.51],[.19,.4,.18]);spike.rotation.x=Math.PI/2;
  const tail=new THREE.Group();body.add(tail);tail.position.set(.43,.77,-.39);block(tail,colors.navy,[.3,.1,0],[.65,.16,.16]);if(fusion){block(tail,colors.yellow,[.6,.36,0],[.2,.65,.12]);let bolt=block(tail,colors.yellow,[.86,.65,0],[.7,.2,.12]);bolt.rotation.z=.4}else block(tail,c,[.58,.36,0],[.2,.65,.16]);
 }else if(kind==='godzilla'||kind==='thermal'){
  block(body,0x376c60,[0,1.15,0],[1.45,1.62,1.05],true);block(body,0x86a78a,[0,1.08,.56],[.88,1.3,.12]);head.position.y=2.15;block(head,0x376c60,[0,.13,.16],[1.18,.75,1],true);block(head,0x54896c,[0,-.08,.72],[.96,.32,.58]);eyes(head,.3,.7,.35);for(const side of [-1,1]){limbs.push(block(body,0x2d6057,[side*.61,.24,.28],[.62,.47,.94]));const a=block(body,0x376c60,[side*.86,1.37,.32],[.34,.77,.4]);a.rotation.x=-.4;limbs.push(a);for(let i=0;i<3;i++)triangle(body,0xfff3d2,[side*.6+(i-1)*.17,.22,.79],[.1,.22,.1])}
  for(let i=0;i<5;i++)triangle(body,colors.cyan,[0,.7+i*.4,-.69],[.51,.66,.29]);for(let i=0;i<6;i++){block(body,0x376c60,[0,.44-i*.04,-.7-i*.43],[.66-i*.075,.55-i*.065,.58]);triangle(body,colors.cyan,[0,.87-i*.08,-.8-i*.43],[.23,.42-i*.04,.22])}
 }else{
  block(body,colors.navy,[0,1.03,0],[1.02,1.3,.8],true);block(body,0x74d9ef,[0,1.01,.46],[.68,.94,.1]);head.position.y=1.85;block(head,colors.navy,[0,.18,.08],[.92,.65,.8],true);block(head,colors.navy,[0,0,.52],[.75,.3,.6]);eyes(head,.28,.52,.29);
  for(const side of [-1,1]){triangle(head,colors.navy,[side*.33,.79,-.16],[.24,.8,.22]);limbs.push(block(body,colors.navy,[side*.41,.22,.2],[.4,.43,.66]));limbs.push(block(body,colors.navy,[side*.64,1.14,.3],[.26,.65,.3]));const w=triangle(body,colors.cyan,[side*1.16,1.6,-.43],[1.05,1.55,.13]);w.rotation.z=-side*.95;ball(head,colors.cyan,[side*.5,.02,.65],[.24,.16,.36]);}for(let i=0;i<4;i++)block(body,colors.navy,[.3+i*.16,.4+i*.08,-.6-i*.29],[.27,.25,.45]);triangle(body,colors.cyan,[.96,.99,-1.58],[.34,.85,.3]);
 }
 if(kind==='thermal'){body.traverse(m=>{if(m.isMesh&&m.material.type==='MeshToonMaterial'){const original=m.material.color.getHex();if(original===0x376c60||original===0x2d6057)m.material=material(0x493444);else if(original===colors.cyan)m.material=material(0xff672c)}})}if(kind==='dragonfusion'){block(head,colors.blue,[0,.2,.4],[.98,.23,.12]);triangle(body,0xffffff,[0,1.1,.6],[.2,.5,.2]).rotation.x=Math.PI/2;for(const side of[-1,1])block(head,colors.navy,[side*.5,-.1,-.26],[.15,.65,.2])}root.userData={body,head,limbs,emblem,kind};return root}
function rebuild(){if(!scene)return;if(hero)scene.remove(hero);if(enemy)scene.remove(enemy);hero=creature(state.hero);enemy=creature(state.enemy);hero.position.set(state.px??-3,0,state.pz??1.5);hero.rotation.y=.52;enemy.position.set(state.ex??3,0,state.ez??-1.5);enemy.rotation.y=-.52;enemy.scale.setScalar((state.enemy==='godzilla'||state.enemy==='thermal')?1.14:1.03);scene.add(hero,enemy)}
function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});}catch(e){$('render-note').textContent='3D unavailable on this browser — illustrated battle fallback is active.';return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.background=new THREE.Color(0xbceafa);scene.fog=new THREE.Fog(0xbceafa,20,45);camera=new THREE.PerspectiveCamera(36,1,.1,80);scene.add(new THREE.HemisphereLight(0xffffff,0x5e9181,3));const sun=new THREE.DirectionalLight(0xfff1d5,3);sun.position.set(-4,8,6);scene.add(sun);
 block(scene,0x62bbaa,[0,-.45,0],[16,.7,11],true);block(scene,0xf3d083,[0,-.08,0],[14,.2,9]);for(let x=-5;x<=5;x++)for(let z=-3;z<=3;z++)if(Math.abs(x)>4||Math.abs(z)>2)shape(scene,cylGeo,0x63baa4,[x,.04,z],[.17,.14,.17],false);
 const circle=new THREE.Mesh(new THREE.RingGeometry(1.05,1.13,40),new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide}));circle.rotation.x=-Math.PI/2;circle.position.set(-2.3,.04,1.1);scene.add(circle);const ring2=circle.clone();ring2.position.set(2.35,.04,-.75);scene.add(ring2);
 for(let i=0;i<9;i++){const x=-7+i*1.8,z=-4.4;block(scene,i%2?0xf9ce49:0x769ad7,[x,.45,z],[1.2,1+i%3*.4,1],true);if(i%3===0){block(scene,0xa583d2,[x,1.4,z],[.7,.65,.7],true)}}
 for(const x of [-6,6]){block(scene,0x685b6c,[x,1.5,-2],[.35,3,.35]);const g=new THREE.Group();g.position.set(x,3.1,-2);block(g,0xf6f5eb,[0,0,0],[.9,.75,.8]);block(g,0xe75569,[0,.2,0],[.96,.4,.85]);block(g,colors.ink,[0,0,.45],[.99,.1,.1]);ball(g,0xffffff,[0,0,.55],[.17,.17,.08]);scene.add(g)}
 for(const o of obstacles){block(scene,0xb59777,[o.x,.45,o.z],[o.r*1.7,.9,o.r*1.7],true);block(scene,0x71bca4,[o.x,.97,o.z],[o.r*1.8,.14,o.r*1.8])}fxGroup=new THREE.Group();scene.add(fxGroup);rebuild();resize()}
function resize(){const r=canvas.parentElement.getBoundingClientRect();if(renderer){renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}else{canvas.width=r.width*devicePixelRatio;canvas.height=r.height*devicePixelRatio}}
const signature={greninja:['💧 Water Shuriken','🥷 Ninja Dash'],fusion:['⚡ Thunder Punch','🐾 Aura Dash'],lucario:['🔵 Aura Sphere','🐾 Extreme Speed'],raichu:['⚡ Thunderbolt','🐾 Quick Attack'],venusaur:['🌿 Vine Whip','🌸 Petal Rush'],dragonfusion:['🔥 Aura Flame','🐉 Dragon Fist'],eevee:['🎀 Ribbon Beam','🐾 Tackle'],surfer:['🌊 Surf','🏄 Board Dash'],rhyhorn:['🪨 Rock Blast','🦏 Horn Charge'],thermal:['🔥 Thermal Pulse','🦖 Tail Smash'],princess:['✨ Star Magic','👑 Royal Spin'],godzilla:['☄ Atomic Breath','🦖 Tail Smash'],charizard:['🔥 Blue Flame','🐉 Dragon Claw']};
function ui(){ $('evolve').disabled=state.hero!=='godzilla'||state.turn<2||state.phase!=='ready'||state.paused;$('team-status').textContent=teamsEnabled?`2v2 tag teams · your backup: ${state.heroReserve?names[state.heroReserve]:'used'} · opponent backup: ${state.enemyReserve?names[state.enemyReserve]:'used'}`:'1v1 arena battle'; $('hero-name').textContent=names[state.hero];$('enemy-name').textContent=names[state.enemy];$('hero-hp').textContent=`${state.hp} / 120 HP`;$('enemy-hp').textContent=`${state.ehp} / ${state.max} HP`;$('hero-bar').style.width=state.hp/120*100+'%';$('enemy-bar').style.width=state.ehp/state.max*100+'%';for(const id of ['water','dash','mega','guard'])$('move-'+id).disabled=state.phase!=='ready'||state.paused;$('fuse').disabled=state.phase!=='ready'||state.paused||state.hero==='fusion';$('greninja').disabled=state.phase!=='ready'||state.paused;$('move-water').textContent=signature[state.hero][0]+' ①';$('move-dash').textContent=signature[state.hero][1]+' ②';$('pause').textContent=state.paused?'Resume':'Pause';}
function log(s){$('log').textContent=s}
function reset(kind=state.startingEnemy??state.enemy,heroKind=state.startingHero??state.hero){$('confetti').replaceChildren();$('battle-splash').classList.remove('on');state={hero:heroKind,enemy:kind,startingHero:heroKind,startingEnemy:kind,hp:120,ehp:(kind==='godzilla'||kind==='thermal')?150:125,max:(kind==='godzilla'||kind==='thermal')?150:125,phase:'ready',age:0,turn:0,guard:false,paused:false,heroReserve:teamsEnabled?heroReserveChoice:null,enemyReserve:teamsEnabled?enemyReserveChoice:null,px:-3,pz:1.5,ex:3,ez:-1.5,aiTimer:2.5,hit:false};clearControls();rebuild();ui();log(realtime?'Move around the blocks. Attack up close, then dodge the red target!':'Choose a move. Your challenger attacks after your turn.');$('callout').textContent=`${names[heroKind].toUpperCase()} vs ${names[kind].toUpperCase()}`}
function move(kind){if(state.phase!=='ready'||state.paused)return;fanfare('move');state.guard=kind==='guard';state.turn++;state.phase='attack';state.age=0;state.move=kind;state.hit=false;state.landed=false;state.aimX=state.ex;state.aimZ=state.ez;if(state.guard){state.hp=Math.min(120,state.hp+20);log('Protect! Hold your shield and recover 20 HP.')}else{const label=kind==='mega'?'MEGA BURST':signature[state.hero][kind==='dash'?1:0].toUpperCase();$('callout').textContent=label+'!';log(`${names[state.hero]} winds up ${label.toLowerCase()}!`)}ui()}
function startCounter(){state.phase='counter';state.age=0;state.hit=false;state.dodged=false;state.aimX=state.px;state.aimZ=state.pz;state.aiTimer=2.8;$('callout').textContent=realtime?'INCOMING! MOVE TO DODGE!':'CHALLENGER ATTACKS!';log(`${names[state.enemy]} is charging an attack!`);ui()}
function stepPosition(x,z,dx,dz){const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));let nx=clamp(x+dx,-6.25,6.25),nz=clamp(z+dz,-3.75,3.75);for(const o of obstacles){const rx=nx-o.x,rz=nz-o.z,d=Math.hypot(rx,rz),r=o.r+.42;if(d<r){if(d>.001){nx=o.x+rx/d*r;nz=o.z+rz/d*r}else nx=o.x+r}}return[nx,nz]}
function clearRoute(a,b){
 const dx=b.x-a.x,dz=b.z-a.z,length2=dx*dx+dz*dz;
 return obstacles.every(o=>{const t=length2?Math.max(0,Math.min(1,((o.x-a.x)*dx+(o.z-a.z)*dz)/length2)):0;return Math.hypot(a.x+dx*t-o.x,a.z+dz*t-o.z)>=o.r+.419})
}
function enemyRoute(){
 // Small visibility graph around the three blocks; paths cannot cut through them.
 const start={x:state.ex,z:state.ez},goal={x:state.px,z:state.pz};if(clearRoute(start,goal))return[goal];
 const nodes=[start,goal];
 for(const o of obstacles)for(let i=0;i<12;i++){
  const a=i*Math.PI/6,p={x:o.x+Math.cos(a)*(o.r+.62),z:o.z+Math.sin(a)*(o.r+.62)};
  if(obstacles.every(other=>Math.hypot(p.x-other.x,p.z-other.z)>other.r+.42))nodes.push(p)
 }
 const distances=nodes.map(()=>Infinity),previous=[],visited=new Set();distances[0]=0;
 for(let i=0;i<nodes.length;i++){
  let current=-1;for(let j=0;j<nodes.length;j++)if(!visited.has(j)&&(current===-1||distances[j]<distances[current]))current=j;
  if(current===1||current===-1||!Number.isFinite(distances[current]))break;visited.add(current);
  for(let j=0;j<nodes.length;j++)if(!visited.has(j)&&clearRoute(nodes[current],nodes[j])){const distance=distances[current]+Math.hypot(nodes[j].x-nodes[current].x,nodes[j].z-nodes[current].z);if(distance<distances[j]){distances[j]=distance;previous[j]=current}}
 }
 if(!Number.isFinite(distances[1]))return[];
 const route=[];for(let i=1;i!==0;i=previous[i])route.unshift(nodes[i]);return route
}
function approachEnemy(dt){
 if(!state.route?.length||Math.hypot(state.px-state.routeTargetX,state.pz-state.routeTargetZ)>.7){state.route=enemyRoute();state.routeTargetX=state.px;state.routeTargetZ=state.pz}
 while(state.route.length>1&&Math.hypot(state.route[0].x-state.ex,state.route[0].z-state.ez)<.12)state.route.shift();
 const next=state.route[0];if(!next)return;const dx=next.x-state.ex,dz=next.z-state.ez,d=Math.hypot(dx,dz),step=Math.min(d,dt*1.05);if(d>0)[state.ex,state.ez]=stepPosition(state.ex,state.ez,dx/d*step,dz/d*step)
}
function updateCombat(dt){state.age+=dt;const terminal=state.phase==='won'||state.phase==='lost';if(!terminal){const oldX=state.px,oldZ=state.pz,oldEX=state.ex,oldEZ=state.ez;let dx=(directionHeld('d')||directionHeld('ArrowRight')?1:0)-(directionHeld('a')||directionHeld('ArrowLeft')?1:0),dz=(directionHeld('s')||directionHeld('ArrowDown')?1:0)-(directionHeld('w')||directionHeld('ArrowUp')?1:0);const n=Math.hypot(dx,dz)||1;[state.px,state.pz]=stepPosition(state.px??-3,state.pz??1.5,dx/n*dt*3.8,dz/n*dt*3.8);state.ex??=3;state.ez??=-1.5;state.aiTimer=(state.aiTimer??2.5)-dt;const distance=Math.hypot(state.ex-state.px,state.ez-state.pz);if(realtime&&distance>3.5&&state.phase!=='counter'){approachEnemy(dt)}state.moving=Math.hypot(state.px-oldX,state.pz-oldZ)>.001;state.enemyMoving=Math.hypot(state.ex-oldEX,state.ez-oldEZ)>.001;if(realtime&&state.phase==='ready'&&state.aiTimer<=0&&distance<4.5)startCounter()}
 if(state.phase==='attack'&&state.age>.5&&!state.hit){state.hit=true;if(!state.guard){const distance=Math.hypot(state.ex-state.px,state.ez-state.pz),reach=state.move==='water'?8:state.move==='mega'?5:3.8;if(!realtime||distance<reach){state.landed=true;const tail=(state.hero==='godzilla'||state.hero==='thermal')&&state.move==='dash',damage=tail?40:state.move==='mega'?36:state.move==='water'?28:30;state.ehp=Math.max(0,state.ehp-damage);if(tail){const d=distance||1;[state.ex,state.ez]=stepPosition(state.ex,state.ez,(state.ex-state.px)/d*1.3,(state.ez-state.pz)/d*1.3);state.route=null}log(`${names[state.enemy]} takes ${damage} damage!`);document.querySelector('.arena').classList.remove('hit');void canvas.offsetWidth;document.querySelector('.arena').classList.add('hit')}else log('Out of range! Move closer for that attack.')}ui()}
 if(state.phase==='attack'&&state.age>1.2){if(state.ehp<=0){state.phase='won';state.age=0;state.celebrated=false;$('callout').textContent=names[state.enemy].toUpperCase()+' FAINTED!';log('TIMBER! A spectacular brick knockout!')}else if(realtime){state.phase='ready';state.age=0;$('callout').textContent='MOVE • ATTACK • DODGE!'}else startCounter();ui()}
 if(state.phase==='counter'&&state.age>.65&&!state.hit){state.hit=true;const dodged=realtime&&Math.hypot(state.px-state.aimX,state.pz-state.aimZ)>1.15;state.dodged=dodged;if(dodged){log('DODGED! Nice footwork!');$('callout').textContent='DODGED!'}else{const damage=state.guard?5:(state.enemy==='godzilla'||state.enemy==='thermal')?19:15;state.hp=Math.max(0,state.hp-damage);log(`${names[state.enemy]} hits for ${damage}!`)}state.guard=false;ui()}
 if(state.phase==='counter'&&state.age>1.25){state.phase=state.hp<=0?'lost':'ready';state.age=0;$('callout').textContent=state.hp<=0?(state.heroReserve?'BACKUP INCOMING!':'REMATCH? YOU CAN DO IT!'):(realtime?'MOVE • ATTACK • DODGE!':'YOUR TURN!');if(state.hp<=0)log(state.heroReserve?`${names[state.hero]} fainted. ${names[state.heroReserve]} is ready to tag in!`:'Your fighter fainted! Tap Rematch for your comeback.');ui()}
 if(state.age>1.55&&((state.phase==='won'&&state.enemyReserve)||(state.phase==='lost'&&state.heroReserve))){
  const heroTags=state.phase==='lost';
  if(heroTags){state.hero=state.heroReserve;state.heroReserve=null;state.hp=120;state.px=-3;state.pz=1.5;state.turn=0}
  else{state.enemy=state.enemyReserve;state.enemyReserve=null;state.max=state.enemy==='godzilla'||state.enemy==='thermal'?150:125;state.ehp=state.max;state.ex=3;state.ez=-1.5}
  state.phase='ready';state.age=0;state.aiTimer=2.5;state.guard=false;state.hit=false;state.route=null;state.move=null;state.moving=false;state.enemyMoving=false;clearControls();rebuild();
  const incoming=names[heroTags?state.hero:state.enemy];$('callout').textContent=incoming.toUpperCase()+' TAGS IN!';log(incoming+' tags in! '+(realtime?'Keep moving and watch for the red target.':'Choose your next move.'));ui()
 }
 if(state.phase==='won'&&state.age>1.65&&!state.celebrated){state.celebrated=true;celebrate();$('callout').textContent=names[state.hero].toUpperCase()+' IS THE CHAMPION!';log('What a finish! Pick another challenger or play a rematch.')}
}
for(const id of ['water','dash','mega','guard'])$('move-'+id).onclick=()=>move(id);$('restart').onclick=()=>reset();$('pause').onclick=()=>{clearControls();state.paused=!state.paused;ui()};document.querySelectorAll('[data-enemy]').forEach(b=>b.onclick=()=>reset(b.dataset.enemy));$('fuse').onclick=()=>{if(state.phase!=='ready'||state.paused)return;state.hero='fusion';state.hp=Math.min(120,state.hp+25);rebuild();$('callout').textContent='LUCARIO + RAICHU = FUSION!';log('Electric aura + fighting power! Your new fusion restores 25 HP.');ui()};$('greninja').onclick=()=>{if(state.phase!=='ready'||state.paused)return;state.hero='greninja';rebuild();$('callout').textContent='MEGA GRENINJA RETURNS!';ui()};addEventListener('keydown',e=>{
 if(!$('roster').hidden||e.target.closest('input,select,textarea')||e.ctrlKey||e.metaKey||e.altKey)return;
 if('1234'.includes(e.key))move(['water','dash','mega','guard'][Number(e.key)-1]);
 if(e.key.toLowerCase()==='f')$('fuse').click();
 const key=movementKey(e);if(['w','a','s','d','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(key)){if(!state.paused)held.add(key);e.preventDefault()}
});
addEventListener('resize',resize);addEventListener('keyup',e=>held.delete(movementKey(e)));addEventListener('blur',clearControls);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearControls()});
function strikeProgress(attacking){const strikeAt=attacking?.5:.65;return Math.min(1,Math.max(0,(state.age-.18)/(strikeAt-.18)))}
function fallback(){const calm=matchMedia('(prefers-reduced-motion: reduce)').matches;const c=canvas.getContext('2d');if(!c)return;const w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#91d9fa');sky.addColorStop(1,'#fff1be');c.fillStyle=sky;c.fillRect(0,0,w,h);c.fillStyle='#71cbb0';c.fillRect(0,h*.72,w,h*.28);for(let i=0;i<25;i++){c.fillStyle=['#f7ce49','#769ad7','#f383a8'][i%3];c.fillRect(i*w/25,h*.59,w/28,h*.12)}for(const o of obstacles){const ox=w*(.5+o.x/16),oy=h*(.62+o.z/30);c.fillStyle='#b59777';c.strokeStyle='#152638';c.lineWidth=3;c.fillRect(ox-w*.035,oy-h*.12,w*.07,h*.12);c.strokeRect(ox-w*.035,oy-h*.12,w*.07,h*.12)}if(state.phase==='counter'&&state.age<.65){c.strokeStyle='#ed4667';c.lineWidth=6;c.beginPath();c.ellipse(w*(.5+state.aimX/16),h*(.62+state.aimZ/30),w*.055,h*.025,0,0,Math.PI*2);c.stroke()}for(const [side,x,kind,col]of[[-1,w*(.5+(state.px??-3)/16),state.hero,'#2774c6'],[1,w*(.5+(state.ex??3)/16),state.enemy,'#407766']]){const fainted=side===1?state.phase==='won':state.phase==='lost',active=side===-1?state.phase==='attack':state.phase==='counter',moving=side===-1?state.moving:state.enemyMoving;c.save();c.translate(x,h*(.62+(side===-1?state.pz:state.ez)/30));if(!calm&&!fainted){if(moving)c.translate(0,-Math.abs(Math.sin(worldTime*11))*h*.012);if(active){const pulse=Math.sin(Math.min(state.age/1.2,1)*Math.PI);c.rotate(-side*pulse*.09);c.translate(side*pulse*w*.012,0)}}if(fainted)c.rotate(side*Math.min(state.age/.85,1)**2*1.5);else if(state.phase==='won'&&!calm)c.translate(0,-Math.abs(Math.sin(worldTime*4))*h*.025);if(!fainted||state.age<1.15){c.fillStyle=col;c.strokeStyle='#152638';c.lineWidth=6;c.fillRect(-w*.06,-h*.34,w*.12,h*.34);c.strokeRect(-w*.06,-h*.34,w*.12,h*.34);c.fillRect(-w*.09,-h*.45,w*.18,h*.17);c.strokeRect(-w*.09,-h*.45,w*.18,h*.17);c.fillStyle='white';c.fillRect(-w*.05,-h*.41,w*.03,h*.035);c.fillRect(w*.02,-h*.41,w*.03,h*.035)}c.restore();if(fainted&&state.age>.85&&state.age<2.7){const t=state.age-.85;for(let i=0;i<42;i++){const a=i*2.39996,v=1+i%7*.14;c.save();c.translate(x+Math.cos(a)*t*w*.13*v,h*.62+(2.7*t*t-2.4*t)*h*.22+Math.sin(a)*t*h*.13);c.rotate(t*5+i);c.globalAlpha=Math.max(0,1-t/1.85);c.fillStyle=['#ffdc35','#5ddcfc','#f578a8','#ffffff'][i%4];c.fillRect(-7,-7,14,14);c.restore()}}c.font=`bold ${Math.max(12,w*.02)}px system-ui`;c.textAlign='center';c.fillStyle='#152638';c.fillText(names[kind],x,h*.9)}drawFallbackAttack(c,w,h,calm)}
function drawFallbackAttack(c,w,h,calm){
 const attacking=state.phase==='attack';if(!attacking&&state.phase!=='counter')return;
 const p=strikeProgress(attacking),sx=w*(.5+(attacking?state.px:state.ex)/16),sy=h*(.42+(attacking?state.pz:state.ez)/30),tx=w*(.5+(attacking?state.ex:state.aimX)/16),ty=h*(.42+(attacking?state.ez:state.aimZ)/30),strikeAt=attacking?.5:.65;
 c.save();c.strokeStyle=attacking?'#168ec9':'#e74e57';c.fillStyle=attacking?'#6ef0ff':'#ffbe68';c.lineWidth=Math.max(3,w*.004);
 if(attacking&&state.guard){c.strokeStyle='#149764';c.fillStyle='#70ffd344';c.beginPath();c.ellipse(sx,sy,w*.1,h*.25,0,0,Math.PI*2);c.fill();c.stroke()}
 else if(state.age<strikeAt){
  if(attacking&&state.move!=='water'){c.beginPath();c.ellipse(sx,h*(.62+state.pz/30),w*(.035+p*.13),h*(.015+p*.035),0,0,Math.PI*2);c.stroke()}
  else{const progress=calm?1:p;c.beginPath();c.moveTo(sx,sy);c.lineTo(sx+(tx-sx)*progress,sy+(ty-sy)*progress);c.stroke();c.beginPath();c.arc(sx+(tx-sx)*progress,sy+(ty-sy)*progress,Math.max(6,w*.012),0,Math.PI*2);c.fill();c.stroke()}
 }else if(state.age<strikeAt+.2&&(attacking?state.landed:!state.dodged)){c.beginPath();c.arc(tx,ty,w*.035,0,Math.PI*2);c.fill();c.stroke()}
 c.restore()
}
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(document.hidden||state.paused)return;worldTime+=dt;updateCombat(dt);if(!renderer){fallback();return}const calm=matchMedia('(prefers-reduced-motion: reduce)').matches;
 for(const [m,side]of[[hero,-1],[enemy,1]]){const d=m.userData,t=calm?0:worldTime,fainted=side===1?state.phase==='won':state.phase==='lost',active=side===-1?state.phase==='attack':state.phase==='counter',p=Math.min(state.age/1.2,1);m.position.set(side===-1?state.px:state.ex,0,side===-1?state.pz:state.ez);m.rotation.y=Math.atan2((side===-1?state.ex-state.px:state.px-state.ex),(side===-1?state.ez-state.pz:state.pz-state.ez));d.body.rotation.set(0,0,0);d.body.position.y=Math.sin(t*2.6+side)*.06;d.head.rotation.z=Math.sin(t*1.7+side)*.035;const walking=side===-1?state.moving:state.enemyMoving;d.limbs.forEach((l,i)=>l.rotation.x=Math.sin(t*(walking?11:2)+i*Math.PI)*(walking?.3:.04));if(d.emblem)d.emblem.rotation.z=t*.8;
 if(active&&!calm){const pulse=Math.sin(p*Math.PI),tail=side===-1&&(state.hero==='godzilla'||state.hero==='thermal')&&state.move==='dash';d.body.position.y+=state.move==='dash'&&!tail?pulse*.5:0;d.body.rotation.z=-side*pulse*.15;d.limbs.forEach((l,i)=>{if(i%2)l.rotation.x=-pulse*1.7});if(tail){d.body.rotation.y=p*Math.PI*2;d.body.position.y+=pulse*.12}else if(state.move==='mega'){d.body.position.y+=pulse*.4;d.body.rotation.y=Math.sin(p*Math.PI*2)*.25}}
 if(fainted){const q=Math.min(state.age/.85,1);m.rotation.z=side*q*q*1.5;m.position.y=-.12*q;m.visible=state.age<1.15;d.body.position.y=0}else if(state.phase==='won'&&side===-1){d.body.position.y=calm?0:Math.abs(Math.sin(worldTime*4))*.3;d.limbs.forEach((l,i)=>{if(i%2===1)l.rotation.z=i<2?-2.4:2.4})}}
 while(fxGroup.children.length){const m=fxGroup.children[0];fxGroup.remove(m);if(!m.userData.shared){m.geometry?.dispose();m.material?.dispose()}}
 const makeFx=(geo,color,x,y,z)=>{const m=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide}));m.position.set(x,y,z);fxGroup.add(m);return m};
 if(state.phase==='attack'||state.phase==='counter'){const attacking=state.phase==='attack',p=strikeProgress(attacking),sx=attacking?state.px:state.ex,sz=attacking?state.pz:state.ez,tx=attacking?state.ex:state.aimX,tz=attacking?state.ez:state.aimZ,color=attacking?(state.hero==='fusion'||state.hero==='raichu'?0xffdd35:0x42dcff):0xff855d;if(attacking&&state.guard){const shield=makeFx(new THREE.SphereGeometry(1.1,16,12),0x79ffb5,sx,1.1,sz);shield.material.wireframe=true}else if(attacking&&state.move==='dash'){const ring=makeFx(new THREE.RingGeometry(.3+2.4*p,.48+2.4*p,32),color,sx,.15,sz);ring.rotation.x=-Math.PI/2;ring.material.opacity=1-p}else if(attacking&&state.move==='mega'){const r=makeFx(new THREE.TorusGeometry(.35+p*3,.1,6,32),0xffdd35,sx,1.1,sz);r.rotation.x=Math.PI/2;const burst=makeFx(new THREE.IcosahedronGeometry(.15+Math.sin(p*Math.PI)*.7,0),color,tx,1.2,tz);burst.rotation.y=worldTime*8}else{for(let i=0;i<12;i++){const q=Math.max(0,p-i*.025),m=makeFx(new THREE.IcosahedronGeometry(.07+(12-i)*.012,0),color,sx+(tx-sx)*q,1.1+Math.sin(q*Math.PI)*.45,sz+(tz-sz)*q);m.rotation.set(worldTime*5,i,worldTime*3)}}if(!attacking&&state.age<.65){const warn=makeFx(new THREE.RingGeometry(.9,1.03,32),0xff566d,state.aimX,.15,state.aimZ);warn.rotation.x=-Math.PI/2}}
 if((state.phase==='won'||state.phase==='lost')&&state.age>.85&&state.age<2.7){const t=state.age-.85,win=state.phase==='won';for(let i=0;i<42;i++){const a=i*2.39996,v=1.5+(i%7)*.35,m=new THREE.Mesh(boxGeo,material([0xffd33d,0x51e9fa,0xf96fa7,0xffffff,0x376c60][i%5]));m.userData.shared=true;m.scale.setScalar(Math.max(.01,.19*(1-t/1.85)));m.position.set((win?state.ex:state.px)+Math.cos(a)*t*v,.7+(2+i%5*.35)*t-2.7*t*t,(win?state.ez:state.pz)+Math.sin(a)*t*v);m.rotation.set(t*5+i,t*7,t*3);fxGroup.add(m)}}const zoom=state.phase==='won'?Math.max(13,16-state.age*.4):16;camera.position.set(Math.sin(.22+orbit)*zoom,9.5,Math.cos(.22+orbit)*zoom);camera.lookAt(0,.8,0);renderer.render(scene,camera)}
const rosterData=[['greninja','#55ccec','WATER / DARK'],['godzilla','#8ed1a2','KING OF MONSTERS'],['charizard','#95a0ee','MEGA / FIRE'],['lucario','#67bce5','MEGA / AURA'],['raichu','#ffcf60','ELECTRIC'],['fusion','#ffa3cd','FIRST FUSION'],['venusaur','#85cf9c','MEGA / GRASS'],['dragonfusion','#ce96fa','FIRE / AURA FUSION'],['eevee','#ffc0da','RIBBONS & BOWS'],['surfer','#ffe96b','PIKACHU / SURFER'],['rhyhorn','#b7c8d5','ROCK / GROUND'],['thermal','#ff9c65','THERMAL EVOLUTION'],['princess','#e1b3ff','ORIGINAL PRINCESS']];
let pickSide='hero',chosenHero='greninja',chosenEnemy='godzilla',chosenTeams=false,chosenRealtime=true,chosenHeroReserve='eevee',chosenEnemyReserve='venusaur',rosterPaused=false,soundOn=false,audio=null;
function portrait(kind,color){const ears=kind==='godzilla'?'<path d="M39 29L43 12L52 30L61 9L69 29" fill="#76ecf2" stroke="#172939" stroke-width="4"/>':kind==='greninja'?'<path d="M27 35L17 4L46 29M75 35L89 4L58 29" fill="#2984c5" stroke="#172939" stroke-width="4"/>':'<path d="M28 35L25 1L43 28M73 35L77 1L58 28" fill="#263447" stroke="#172939" stroke-width="4"/>';return `<svg viewBox="0 0 100 100" aria-hidden="true">${ears}<rect x="25" y="62" width="50" height="34" rx="5" fill="${color}" stroke="#172939" stroke-width="4"/><rect x="16" y="26" width="69" height="43" rx="7" fill="${color}" stroke="#172939" stroke-width="4"/><rect x="24" y="41" width="19" height="12" fill="white" stroke="#172939" stroke-width="2"/><rect x="57" y="41" width="19" height="12" fill="white" stroke="#172939" stroke-width="2"/><rect x="34" y="42" width="6" height="11" fill="#172939"/><rect x="60" y="42" width="6" height="11" fill="#172939"/>${kind==='greninja'?'<path d="M19 65H85L94 76L32 74Z" fill="#fc7aad" stroke="#172939" stroke-width="3"/>':kind==='fusion'||kind==='raichu'?'<circle cx="24" cy="57" r="7" fill="#ffdd31"/><circle cx="76" cy="57" r="7" fill="#ffdd31"/>':''}<rect x="33" y="21" width="12" height="8" rx="2" fill="${color}" stroke="#172939" stroke-width="3"/><rect x="58" y="21" width="12" height="8" rx="2" fill="${color}" stroke="#172939" stroke-width="3"/></svg>`}
function drawRoster(){$('roster-teams').checked=chosenTeams;$('roster-realtime').checked=chosenRealtime;$('backup-picker').hidden=!chosenTeams;for(const [id,selected]of[['hero-backup',chosenHeroReserve],['enemy-backup',chosenEnemyReserve]]){$(id).innerHTML=rosterData.map(([kind])=>`<option value="${kind}" ${kind===selected?'selected':''}>${names[kind]}</option>`).join('')} $('roster-grid').innerHTML=rosterData.map(([kind,color,tag])=>`<button class="fighter-tile" style="--fighter:${color}" data-fighter="${kind}" aria-pressed="${(pickSide==='hero'?chosenHero:chosenEnemy)===kind}"><span class="badge">${kind===chosenHero?'1P':kind===chosenEnemy?'CPU':'✦'}</span>${portrait(kind,color)}<strong>${names[kind]}</strong><small style="font-size:9px">${tag}</small></button>`).join('');document.querySelectorAll('[data-fighter]').forEach(b=>b.onclick=()=>{if(pickSide==='hero')chosenHero=b.dataset.fighter;else chosenEnemy=b.dataset.fighter;fanfare('pick');drawRoster();document.querySelector(`[data-fighter="${b.dataset.fighter}"]`)?.focus()});$('pick-hero-name').textContent=names[chosenHero];$('pick-enemy-name').textContent=names[chosenEnemy];$('pick-hero').setAttribute('aria-pressed',pickSide==='hero');$('pick-enemy').setAttribute('aria-pressed',pickSide==='enemy')}
function setRosterOpen(open){$('roster').hidden=!open;document.querySelectorAll('header, main').forEach(el=>el.inert=open)}
function openRoster(){rosterPaused=state.paused;state.paused=true;clearControls();chosenHero=state.startingHero??state.hero;chosenEnemy=state.startingEnemy??state.enemy;chosenTeams=teamsEnabled;chosenRealtime=realtime;chosenHeroReserve=heroReserveChoice;chosenEnemyReserve=enemyReserveChoice;setRosterOpen(true);drawRoster();ui();$('pick-hero').focus()}
function closeRoster(){clearControls();state.paused=rosterPaused;setRosterOpen(false);ui();$('roster-open').focus()}
function updateModeUI(){$('team-mode').textContent=teamsEnabled?'2v2 tag teams ✓':'1v1 battle';$('combat-mode').textContent=realtime?'Real-time ✓':'Turn-based'}
function splash(text){const el=$('battle-splash');el.querySelector('span').textContent=text;el.classList.remove('on');void el.offsetWidth;el.classList.add('on');setTimeout(()=>el.classList.remove('on'),1500)}
function fanfare(kind){if(!soundOn)return;audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='win'?[523,659,784,1047,1319]:kind==='start'?[392,523,784]:kind==='move'?[330,660]:[660];notes.forEach((hz,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime+i*.1;osc.type='triangle';osc.frequency.value=hz;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.045,t+.01);gain.gain.exponentialRampToValueAtTime(.001,t+.24);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+.25)})}
function celebrate(){splash('CHAMPION! ★');fanfare('win');const host=$('confetti');host.replaceChildren();for(let i=0;i<140;i++){const bit=document.createElement('i');bit.className='confetti-bit';bit.style.cssText=`left:${(i*47)%100}%;--color:${['#ffcf36','#f45380','#67d9f0','#9779ee','#7ad5a6'][i%5]};--duration:${2.1+i%9*.19}s;--delay:${i%7*.06}s;--drift:${(i%11-5)*22}px;--static-top:${i%100}%;border-radius:${i%3===0?'50%':'2px'}`;host.appendChild(bit)}setTimeout(()=>host.replaceChildren(),4500)}
$('roster-open').onclick=openRoster;$('roster-close').onclick=closeRoster;$('pick-hero').onclick=()=>{pickSide='hero';drawRoster()};$('pick-enemy').onclick=()=>{pickSide='enemy';drawRoster()};$('fight-start').onclick=()=>{teamsEnabled=chosenTeams;realtime=chosenRealtime;heroReserveChoice=chosenHeroReserve;enemyReserveChoice=chosenEnemyReserve;setRosterOpen(false);updateModeUI();reset(chosenEnemy,chosenHero);$('move-water').focus();splash('BRICK BATTLE!');fanfare('start')};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'Sound on ♪':'Sound off ♪';if(soundOn)fanfare('pick')};addEventListener('keydown',e=>{
 if($('roster').hidden)return;
 if(e.key==='Escape'){e.preventDefault();closeRoster()}
 if(e.key==='Tab'){const controls=[...$('roster').querySelectorAll('button,select,input')].filter(el=>!el.disabled&&!el.closest('[hidden]')),first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
});
$('hero-backup').onchange=e=>chosenHeroReserve=e.target.value;$('enemy-backup').onchange=e=>chosenEnemyReserve=e.target.value;
$('roster-teams').onchange=e=>{chosenTeams=e.target.checked;$('backup-picker').hidden=!chosenTeams};$('roster-realtime').onchange=e=>chosenRealtime=e.target.checked;
$('team-mode').onclick=()=>{openRoster();chosenTeams=!teamsEnabled;drawRoster()};
$('evolve').onclick=()=>{if(state.hero!=='godzilla'||state.turn<2||state.phase!=='ready'||state.paused)return;state.hero='thermal';rebuild();ui();splash('THERMAL GODZILLA!');log('Godzilla evolves! The arena is heating up!')};
$('combat-mode').onclick=()=>{openRoster();chosenRealtime=!realtime;drawRoster()};
document.querySelectorAll('[data-direction]').forEach(b=>{const clear=e=>touchHeld.delete(e.pointerId);b.onpointerdown=e=>{if(state.paused||!$('roster').hidden)return;touchHeld.set(e.pointerId,b.dataset.direction);b.setPointerCapture(e.pointerId);e.preventDefault()};b.onpointerup=clear;b.onpointercancel=clear;b.onlostpointercapture=clear});
init();reset();resize();frame();openRoster();
