import * as THREE from 'three';
const $=id=>document.getElementById(id);
const names={greninja:'Mega Greninja',fusion:'Lucario × Raichu',godzilla:'Godzilla',charizard:'Mega Charizard X',lucario:'Mega Lucario',raichu:'Raichu'};
let state={hero:'greninja',enemy:'godzilla',hp:120,ehp:150,max:150,phase:'ready',age:0,turn:0,guard:false,paused:false};
let renderer=null,scene,camera,hero,enemy,fxGroup,orbit=0,clock=new THREE.Clock(),worldTime=0;
const canvas=$('battle'),colors={ink:0x172939,blue:0x176dc3,navy:0x182750,cyan:0x51e9fa,pink:0xf96fa7,yellow:0xffd33d,orange:0xffa23a};
const materials=new Map();function material(c){if(!materials.has(c))materials.set(c,new THREE.MeshToonMaterial({color:c}));return materials.get(c)}
const boxGeo=new THREE.BoxGeometry(1,1,1),ballGeo=new THREE.SphereGeometry(1,10,8),coneGeo=new THREE.ConeGeometry(1,1,4),cylGeo=new THREE.CylinderGeometry(1,1,1,12);
function shape(g,geo,c,p,s,outline=true){const m=new THREE.Mesh(geo,material(c));m.position.set(...p);m.scale.set(...s);g.add(m);if(outline){const o=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:colors.ink,side:THREE.BackSide}));o.scale.setScalar(1.06);m.add(o)}return m}
function block(g,c,p,s,stud=false){const m=shape(g,boxGeo,c,p,s);if(stud){for(const x of [-.27,.27])shape(g,cylGeo,c,[p[0]+x*s[0],p[1]+s[1]/2+.06,p[2]],[.12,.13,.12],false)}return m}
function ball(g,c,p,s){return shape(g,ballGeo,c,p,s)}
function triangle(g,c,p,s){return shape(g,coneGeo,c,p,s)}
function eyes(g,y,z,wide=.27){for(const side of [-1,1]){block(g,0xffffff,[side*wide,y,z],[.29,.22,.07]);block(g,0x122133,[side*wide,y-.015,z+.055],[.095,.15,.04])}}
function creature(kind){const root=new THREE.Group(),body=new THREE.Group();root.add(body);let head=new THREE.Group();body.add(head);head.position.y=1.45;const limbs=[];let emblem;
 if(kind==='greninja'){
  block(body,colors.navy,[0,.91,0],[.75,.91,.57],true);block(body,0xf5dd91,[0,.9,.32],[.42,.55,.08]);block(head,colors.blue,[0,.2,0],[1.06,.6,.67],true);eyes(head,.22,.37,.31);
  for(const side of [-1,1]){const horn=triangle(head,colors.blue,[side*.5,.66,-.12],[.27,.65,.24]);horn.rotation.z=-side*.55;const foot=block(body,colors.blue,[side*.47,.15,.12],[.65,.24,.77]);limbs.push(foot);const arm=block(body,colors.blue,[side*.64,.95,.08],[.22,.8,.23]);arm.rotation.z=side*.45;limbs.push(arm);ball(body,colors.cyan,[side*.83,.63,.13],[.18,.12,.2])}
  block(body,colors.pink,[0,1.37,0],[.98,.18,.75]);const scarf=block(body,colors.pink,[.85,1.25,-.32],[1.2,.2,.22]);scarf.rotation.z=-.16;
  emblem=new THREE.Group();body.add(emblem);emblem.position.set(0,1.1,-.65);for(let i=0;i<4;i++){const blade=triangle(emblem,colors.cyan,[Math.sin(i*Math.PI/2)*.6,Math.cos(i*Math.PI/2)*.6,0],[.38,.95,.12]);blade.rotation.z=-i*Math.PI/2}ball(emblem,0xdbffff,[0,0,0],[.23,.23,.12]);
 }else if(kind==='fusion'||kind==='lucario'||kind==='raichu'){
  const fusion=kind==='fusion'||kind==='raichu',c=fusion?colors.orange:0x49a4d9;block(body,c,[0,.98,0],[.72,1.03,.58],true);block(body,0xffe6a2,[0,1.02,.35],[.65,.55,.16]);head.position.y=1.66;block(head,c,[0,.13,0],[.9,.56,.66],true);block(head,colors.navy,[0,.1,.35],[1,.23,.1]);eyes(head,.14,.43,.28);
  for(const side of [-1,1]){const ear=triangle(head,fusion?colors.yellow:colors.navy,[side*.34,.73,-.06],[.27,1,.22]);ear.rotation.z=side*-.18;block(head,colors.ink,[side*.52,-.15,-.28],[.2,.5,.16]);limbs.push(block(body,colors.navy,[side*.35,.23,.05],[.32,.45,.58]));const arm=block(body,c,[side*.57,1,.1],[.25,.75,.29]);arm.rotation.z=side*.25;limbs.push(arm);triangle(body,0xffffff,[side*.64,.92,.32],[.17,.26,.17]);if(fusion)ball(head,colors.yellow,[side*.43,-.05,.37],[.16,.13,.07])}
  const spike=triangle(body,0xffffff,[0,1.03,.51],[.19,.4,.18]);spike.rotation.x=Math.PI/2;
  const tail=new THREE.Group();body.add(tail);tail.position.set(.43,.77,-.39);block(tail,colors.navy,[.3,.1,0],[.65,.16,.16]);if(fusion){block(tail,colors.yellow,[.6,.36,0],[.2,.65,.12]);let bolt=block(tail,colors.yellow,[.86,.65,0],[.7,.2,.12]);bolt.rotation.z=.4}else block(tail,c,[.58,.36,0],[.2,.65,.16]);
 }else if(kind==='godzilla'){
  block(body,0x376c60,[0,1.15,0],[1.45,1.62,1.05],true);block(body,0x86a78a,[0,1.08,.56],[.88,1.3,.12]);head.position.y=2.15;block(head,0x376c60,[0,.13,.16],[1.18,.75,1],true);block(head,0x54896c,[0,-.08,.72],[.96,.32,.58]);eyes(head,.3,.7,.35);for(const side of [-1,1]){limbs.push(block(body,0x2d6057,[side*.61,.24,.28],[.62,.47,.94]));const a=block(body,0x376c60,[side*.86,1.37,.32],[.34,.77,.4]);a.rotation.x=-.4;limbs.push(a);for(let i=0;i<3;i++)triangle(body,0xfff3d2,[side*.6+(i-1)*.17,.22,.79],[.1,.22,.1])}
  for(let i=0;i<5;i++)triangle(body,colors.cyan,[0,.7+i*.4,-.69],[.51,.66,.29]);for(let i=0;i<6;i++){block(body,0x376c60,[0,.44-i*.04,-.7-i*.43],[.66-i*.075,.55-i*.065,.58]);triangle(body,colors.cyan,[0,.87-i*.08,-.8-i*.43],[.23,.42-i*.04,.22])}
 }else{
  block(body,colors.navy,[0,1.03,0],[1.02,1.3,.8],true);block(body,0x74d9ef,[0,1.01,.46],[.68,.94,.1]);head.position.y=1.85;block(head,colors.navy,[0,.18,.08],[.92,.65,.8],true);block(head,colors.navy,[0,0,.52],[.75,.3,.6]);eyes(head,.28,.52,.29);
  for(const side of [-1,1]){triangle(head,colors.navy,[side*.33,.79,-.16],[.24,.8,.22]);limbs.push(block(body,colors.navy,[side*.41,.22,.2],[.4,.43,.66]));limbs.push(block(body,colors.navy,[side*.64,1.14,.3],[.26,.65,.3]));const w=triangle(body,colors.cyan,[side*1.16,1.6,-.43],[1.05,1.55,.13]);w.rotation.z=-side*.95;ball(head,colors.cyan,[side*.5,.02,.65],[.24,.16,.36]);}for(let i=0;i<4;i++)block(body,colors.navy,[.3+i*.16,.4+i*.08,-.6-i*.29],[.27,.25,.45]);triangle(body,colors.cyan,[.96,.99,-1.58],[.34,.85,.3]);
 }
 root.userData={body,head,limbs,emblem,kind};return root}
function rebuild(){if(!scene)return;if(hero)scene.remove(hero);if(enemy)scene.remove(enemy);hero=creature(state.hero);enemy=creature(state.enemy);hero.position.set(-2.3,0,1.1);hero.rotation.y=.52;enemy.position.set(2.35,0,-.75);enemy.rotation.y=-.52;enemy.scale.setScalar(state.enemy==='godzilla'?1.14:1.03);scene.add(hero,enemy)}
function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});}catch(e){$('render-note').textContent='3D unavailable on this browser — illustrated battle fallback is active.';return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.background=new THREE.Color(0xbceafa);scene.fog=new THREE.Fog(0xbceafa,20,45);camera=new THREE.PerspectiveCamera(36,1,.1,80);scene.add(new THREE.HemisphereLight(0xffffff,0x5e9181,3));const sun=new THREE.DirectionalLight(0xfff1d5,3);sun.position.set(-4,8,6);scene.add(sun);
 block(scene,0x62bbaa,[0,-.45,0],[11,.7,7],true);block(scene,0xf3d083,[0,-.08,0],[8.5,.2,5.8]);for(let x=-5;x<=5;x++)for(let z=-3;z<=3;z++)if(Math.abs(x)>4||Math.abs(z)>2)shape(scene,cylGeo,0x63baa4,[x,.04,z],[.17,.14,.17],false);
 const circle=new THREE.Mesh(new THREE.RingGeometry(1.05,1.13,40),new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide}));circle.rotation.x=-Math.PI/2;circle.position.set(-2.3,.04,1.1);scene.add(circle);const ring2=circle.clone();ring2.position.set(2.35,.04,-.75);scene.add(ring2);
 for(let i=0;i<9;i++){const x=-7+i*1.8,z=-4.4;block(scene,i%2?0xf9ce49:0x769ad7,[x,.45,z],[1.2,1+i%3*.4,1],true);if(i%3===0){block(scene,0xa583d2,[x,1.4,z],[.7,.65,.7],true)}}
 for(const x of [-6,6]){block(scene,0x685b6c,[x,1.5,-2],[.35,3,.35]);const g=new THREE.Group();g.position.set(x,3.1,-2);block(g,0xf6f5eb,[0,0,0],[.9,.75,.8]);block(g,0xe75569,[0,.2,0],[.96,.4,.85]);block(g,colors.ink,[0,0,.45],[.99,.1,.1]);ball(g,0xffffff,[0,0,.55],[.17,.17,.08]);scene.add(g)}
 fxGroup=new THREE.Group();scene.add(fxGroup);rebuild();resize()}
function resize(){const r=canvas.parentElement.getBoundingClientRect();if(renderer){renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}else{canvas.width=r.width*devicePixelRatio;canvas.height=r.height*devicePixelRatio}}
const signature={greninja:['💧 Water Shuriken','🥷 Ninja Dash'],fusion:['⚡ Thunder Punch','🐾 Aura Dash'],lucario:['🔵 Aura Sphere','🐾 Extreme Speed'],raichu:['⚡ Thunderbolt','🐾 Quick Attack'],godzilla:['☄ Atomic Breath','🦖 Tail Smash'],charizard:['🔥 Blue Flame','🐉 Dragon Claw']};
function ui(){ $('hero-name').textContent=names[state.hero];$('enemy-name').textContent=names[state.enemy];$('hero-hp').textContent=`${state.hp} / 120 HP`;$('enemy-hp').textContent=`${state.ehp} / ${state.max} HP`;$('hero-bar').style.width=state.hp/120*100+'%';$('enemy-bar').style.width=state.ehp/state.max*100+'%';for(const id of ['water','dash','mega','guard'])$('move-'+id).disabled=state.phase!=='ready'||state.paused;$('fuse').disabled=state.phase!=='ready'||state.paused||state.hero==='fusion';$('greninja').disabled=state.phase!=='ready'||state.paused;$('move-water').textContent=signature[state.hero][0]+' ①';$('move-dash').textContent=signature[state.hero][1]+' ②';$('pause').textContent=state.paused?'Resume':'Pause';}
function log(s){$('log').textContent=s}
function reset(kind=state.enemy,heroKind=state.hero){$('confetti').replaceChildren();$('battle-splash').classList.remove('on');state={hero:heroKind,enemy:kind,hp:120,ehp:kind==='godzilla'?150:125,max:kind==='godzilla'?150:125,phase:'ready',age:0,turn:0,guard:false,paused:false};rebuild();ui();log('Choose a move! The Mega battle begins!');$('callout').textContent=`${names[heroKind].toUpperCase()} vs ${names[kind].toUpperCase()}`}
function move(kind){if(state.phase!=='ready'||state.paused)return;fanfare('move');document.querySelector('.arena').classList.remove('hit');void canvas.offsetWidth;document.querySelector('.arena').classList.add('hit');state.guard=kind==='guard';state.turn++;state.phase='attack';state.age=0;state.move=kind;if(state.guard){state.hp=Math.min(120,state.hp+20);log('Protect! A shield appears and restores 20 HP.')}else{const damage=kind==='mega'?36:kind==='water'?28:24;state.ehp=Math.max(0,state.ehp-damage);const label=kind==='mega'?'MEGA BURST':kind==='dash'?signature[state.hero][1].toUpperCase():signature[state.hero][0].toUpperCase();$('callout').textContent=label+'!';log(`${names[state.hero]} uses ${label.toLowerCase()}! −${damage} HP`)}ui()}
for(const id of ['water','dash','mega','guard'])$('move-'+id).onclick=()=>move(id);$('restart').onclick=()=>reset();$('pause').onclick=()=>{state.paused=!state.paused;ui()};document.querySelectorAll('[data-enemy]').forEach(b=>b.onclick=()=>reset(b.dataset.enemy));$('fuse').onclick=()=>{if(state.phase!=='ready'||state.paused)return;state.hero='fusion';state.hp=Math.min(120,state.hp+25);rebuild();$('callout').textContent='LUCARIO + RAICHU = FUSION!';log('Electric aura + fighting power! Your new fusion restores 25 HP.');ui()};$('greninja').onclick=()=>{if(state.phase!=='ready'||state.paused)return;state.hero='greninja';rebuild();$('callout').textContent='MEGA GRENINJA RETURNS!';ui()};addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea'))return;if('1234'.includes(e.key))move(['water','dash','mega','guard'][Number(e.key)-1]);if(e.key.toLowerCase()==='f')$('fuse').click();if(e.key==='ArrowLeft'){orbit-=.12;e.preventDefault()}if(e.key==='ArrowRight'){orbit+=.12;e.preventDefault()}});addEventListener('resize',resize);
function fallback(){const c=canvas.getContext('2d');if(!c)return;const w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#91d9fa');sky.addColorStop(1,'#fff1be');c.fillStyle=sky;c.fillRect(0,0,w,h);c.fillStyle='#71cbb0';c.fillRect(0,h*.72,w,h*.28);for(let i=0;i<25;i++){c.fillStyle=['#f7ce49','#769ad7','#f383a8'][i%3];c.fillRect(i*w/25,h*.59,w/28,h*.12)}for(const [side,x,kind,col]of[[-1,w*.27,state.hero,'#2774c6'],[1,w*.72,state.enemy,'#407766']]){const fainted=side===1?state.phase==='won':state.phase==='lost';c.save();c.translate(x,h*.7);if(fainted)c.rotate(side*Math.min(state.age/.85,1)**2*1.5);else if(state.phase==='won')c.translate(0,-Math.abs(Math.sin(worldTime*4))*h*.025);if(!fainted||state.age<1.15){c.fillStyle=col;c.strokeStyle='#152638';c.lineWidth=6;c.fillRect(-w*.06,-h*.34,w*.12,h*.34);c.strokeRect(-w*.06,-h*.34,w*.12,h*.34);c.fillRect(-w*.09,-h*.45,w*.18,h*.17);c.strokeRect(-w*.09,-h*.45,w*.18,h*.17);c.fillStyle='white';c.fillRect(-w*.05,-h*.41,w*.03,h*.035);c.fillRect(w*.02,-h*.41,w*.03,h*.035)}c.restore();if(fainted&&state.age>.85&&state.age<2.7){const t=state.age-.85;for(let i=0;i<42;i++){const a=i*2.39996,v=1+i%7*.14;c.save();c.translate(x+Math.cos(a)*t*w*.13*v,h*.62+(2.7*t*t-2.4*t)*h*.22+Math.sin(a)*t*h*.13);c.rotate(t*5+i);c.globalAlpha=Math.max(0,1-t/1.85);c.fillStyle=['#ffdc35','#5ddcfc','#f578a8','#ffffff'][i%4];c.fillRect(-7,-7,14,14);c.restore()}}c.font=`bold ${Math.max(12,w*.02)}px system-ui`;c.textAlign='center';c.fillStyle='#152638';c.fillText(names[kind],x,h*.9)}}
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(document.hidden||state.paused)return;worldTime+=dt;state.age+=dt;if(state.phase==='attack'&&state.age>1.1){if(state.ehp<=0){state.phase='won';state.age=0;state.celebrated=false;$('callout').textContent=names[state.enemy].toUpperCase()+' FAINTED!';log('TIMBER! A spectacular brick knockout!')}else{state.phase='counter';state.age=0;const damage=state.guard?5:state.enemy==='godzilla'?19:15;state.hp=Math.max(0,state.hp-damage);$('callout').textContent=state.enemy==='godzilla'?'ATOMIC BRICK BREATH!':'MEGA COUNTER!';log(`${names[state.enemy]} attacks! ${state.guard?'Your shield helps! ':''}−${damage} HP`)}ui()}if(state.phase==='counter'&&state.age>1.1){state.phase=state.hp<=0?'lost':'ready';$('callout').textContent=state.hp<=0?'REMATCH? YOU CAN DO IT!':'YOUR TURN!';if(state.hp<=0){state.age=0;log('Your fighter fainted! Tap Rematch for your comeback.')}ui()}if(state.phase==='won'&&state.age>1.65&&!state.celebrated){state.celebrated=true;celebrate();$('callout').textContent=names[state.hero].toUpperCase()+' IS THE CHAMPION!';log('What a finish! Pick another challenger or play a rematch.')} 
 if(!renderer){fallback();return}const calm=matchMedia('(prefers-reduced-motion: reduce)').matches;for(const [m,side]of[[hero,-1],[enemy,1]]){const d=m.userData,t=calm?0:worldTime;d.body.position.y=Math.sin(t*2.6+side)*.06;d.head.rotation.z=Math.sin(t*1.7+side)*.035;d.limbs.forEach((l,i)=>l.rotation.x=Math.sin(t*2+i)*.04);if(d.emblem)d.emblem.rotation.z=t*.8;const active=side===-1?state.phase==='attack':state.phase==='counter';m.position.x=side===-1?-2.3:2.35;if(active&&!calm)m.position.x-=side*Math.sin(Math.min(state.age,1)*Math.PI)*.8;const fainted=side===1?state.phase==='won':state.phase==='lost';if(fainted){const p=Math.min(state.age/.85,1);m.rotation.z=side*p*p*1.5;m.position.y=-.12*p;m.visible=state.age<1.15;d.body.position.y=0;d.head.rotation.z=0;d.limbs.forEach(l=>l.rotation.x=0)}else if(state.phase==='won'&&side===-1){d.body.position.y=calm?0:Math.abs(Math.sin(worldTime*4))*.3;d.limbs.forEach((l,i)=>{if(i%2===1)l.rotation.z=i<2?-2.4:2.4})}}
 while(fxGroup.children.length){const m=fxGroup.children[0];fxGroup.remove(m);if(!m.userData.shared){m.geometry?.dispose();m.material?.dispose()}}if(state.phase==='attack'||state.phase==='counter'){const attacking=state.phase==='attack',p=Math.min(state.age/1.1,1),x=attacking?-2.3+4.65*p:2.35-4.65*p,z=attacking?1.1-1.85*p:-.75+1.85*p;for(let i=0;i<7;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.12+i*.025,0),new THREE.MeshBasicMaterial({color:state.guard?0x79ffb5:attacking?(state.hero==='fusion'?0xffd846:0x42dcff):0xb6ff7d}));m.position.set(x+Math.sin(i+worldTime*8)*.3,1.1+Math.cos(i+worldTime*8)*.3,z);m.rotation.set(worldTime*4,i,worldTime*3);fxGroup.add(m)}}if((state.phase==='won'||state.phase==='lost')&&state.age>.85&&state.age<2.7){const t=state.age-.85,side=state.phase==='won'?1:-1;for(let i=0;i<42;i++){const a=i*2.39996,v=1.5+(i%7)*.35,m=new THREE.Mesh(boxGeo,material([0xffd33d,0x51e9fa,0xf96fa7,0xffffff,0x376c60][i%5]));m.userData.shared=true;m.scale.setScalar(Math.max(.01,.19*(1-t/1.85)));m.position.set((side===1?2.35:-2.3)+Math.cos(a)*t*v,.7+(2+i%5*.35)*t-2.7*t*t,(side===1?-.75:1.1)+Math.sin(a)*t*v);m.rotation.set(t*5+i,t*7,t*3);fxGroup.add(m)}}const zoom=state.phase==='won'?Math.max(10.5,12.1-state.age*.4):12.1;camera.position.set(Math.sin(.32+orbit)*zoom,6.6,Math.cos(.32+orbit)*zoom);camera.lookAt(state.phase==='won'?-.5:0,1.05,0);renderer.render(scene,camera)}
const rosterData=[['greninja','#55ccec','WATER / DARK'],['godzilla','#8ed1a2','KING OF MONSTERS'],['charizard','#95a0ee','MEGA / FIRE'],['lucario','#67bce5','MEGA / AURA'],['raichu','#ffcf60','ELECTRIC'],['fusion','#ffa3cd','FIRST FUSION']];
let pickSide='hero',chosenHero='greninja',chosenEnemy='godzilla',rosterPaused=false,soundOn=false,audio=null;
function portrait(kind,color){const ears=kind==='godzilla'?'<path d="M39 29L43 12L52 30L61 9L69 29" fill="#76ecf2" stroke="#172939" stroke-width="4"/>':kind==='greninja'?'<path d="M27 35L17 4L46 29M75 35L89 4L58 29" fill="#2984c5" stroke="#172939" stroke-width="4"/>':'<path d="M28 35L25 1L43 28M73 35L77 1L58 28" fill="#263447" stroke="#172939" stroke-width="4"/>';return `<svg viewBox="0 0 100 100" aria-hidden="true">${ears}<rect x="25" y="62" width="50" height="34" rx="5" fill="${color}" stroke="#172939" stroke-width="4"/><rect x="16" y="26" width="69" height="43" rx="7" fill="${color}" stroke="#172939" stroke-width="4"/><rect x="24" y="41" width="19" height="12" fill="white" stroke="#172939" stroke-width="2"/><rect x="57" y="41" width="19" height="12" fill="white" stroke="#172939" stroke-width="2"/><rect x="34" y="42" width="6" height="11" fill="#172939"/><rect x="60" y="42" width="6" height="11" fill="#172939"/>${kind==='greninja'?'<path d="M19 65H85L94 76L32 74Z" fill="#fc7aad" stroke="#172939" stroke-width="3"/>':kind==='fusion'||kind==='raichu'?'<circle cx="24" cy="57" r="7" fill="#ffdd31"/><circle cx="76" cy="57" r="7" fill="#ffdd31"/>':''}<rect x="33" y="21" width="12" height="8" rx="2" fill="${color}" stroke="#172939" stroke-width="3"/><rect x="58" y="21" width="12" height="8" rx="2" fill="${color}" stroke="#172939" stroke-width="3"/></svg>`}
function drawRoster(){ $('roster-grid').innerHTML=rosterData.map(([kind,color,tag])=>`<button class="fighter-tile" style="--fighter:${color}" data-fighter="${kind}" aria-pressed="${(pickSide==='hero'?chosenHero:chosenEnemy)===kind}"><span class="badge">${kind===chosenHero?'1P':kind===chosenEnemy?'CPU':'✦'}</span>${portrait(kind,color)}<strong>${names[kind]}</strong><small style="font-size:9px">${tag}</small></button>`).join('');document.querySelectorAll('[data-fighter]').forEach(b=>b.onclick=()=>{if(pickSide==='hero')chosenHero=b.dataset.fighter;else chosenEnemy=b.dataset.fighter;fanfare('pick');drawRoster()});$('pick-hero-name').textContent=names[chosenHero];$('pick-enemy-name').textContent=names[chosenEnemy];$('pick-hero').setAttribute('aria-pressed',pickSide==='hero');$('pick-enemy').setAttribute('aria-pressed',pickSide==='enemy')}
function openRoster(){rosterPaused=state.paused;state.paused=true;chosenHero=state.hero;chosenEnemy=state.enemy;$('roster').hidden=false;drawRoster();ui();$('pick-hero').focus()}
function closeRoster(){state.paused=rosterPaused;$('roster').hidden=true;ui();$('roster-open').focus()}
function splash(text){const el=$('battle-splash');el.querySelector('span').textContent=text;el.classList.remove('on');void el.offsetWidth;el.classList.add('on');setTimeout(()=>el.classList.remove('on'),1500)}
function fanfare(kind){if(!soundOn)return;audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='win'?[523,659,784,1047,1319]:kind==='start'?[392,523,784]:kind==='move'?[330,660]:[660];notes.forEach((hz,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime+i*.1;osc.type='triangle';osc.frequency.value=hz;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.045,t+.01);gain.gain.exponentialRampToValueAtTime(.001,t+.24);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+.25)})}
function celebrate(){splash('CHAMPION! ★');fanfare('win');const host=$('confetti');host.replaceChildren();for(let i=0;i<140;i++){const bit=document.createElement('i');bit.className='confetti-bit';bit.style.cssText=`left:${(i*47)%100}%;--color:${['#ffcf36','#f45380','#67d9f0','#9779ee','#7ad5a6'][i%5]};--duration:${2.1+i%9*.19}s;--delay:${i%7*.06}s;--drift:${(i%11-5)*22}px;--static-top:${i%100}%;border-radius:${i%3===0?'50%':'2px'}`;host.appendChild(bit)}setTimeout(()=>host.replaceChildren(),4500)}
$('roster-open').onclick=openRoster;$('roster-close').onclick=closeRoster;$('pick-hero').onclick=()=>{pickSide='hero';drawRoster()};$('pick-enemy').onclick=()=>{pickSide='enemy';drawRoster()};$('fight-start').onclick=()=>{$('roster').hidden=true;reset(chosenEnemy,chosenHero);splash('BRICK BATTLE!');fanfare('start')};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'Sound on ♪':'Sound off ♪';if(soundOn)fanfare('pick')};addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('roster').hidden)closeRoster()});
init();ui();resize();frame();openRoster();
